spring.application.name=foodlocation
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Saravanan@99
server.ssl.key-store-tycdpe=PKCS12
server.ssl.key-alias=springboot